---
title: 'Data Analysis 1'
output:
  html_notebook:
    toc: true
    number_sections: true
  pdf_document: default
---

# Basic Care and Feeding Data into R
http://stat545.com/block006_care-feeding-data.html

```{r}
library(gapminder)
library(tidyverse)

# some visualizations of the data

p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point() # scatterplot
p + geom_point(aes(color = continent)) # map continent to color
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)

# but can we make it plotly?

```




# Split Apply Combine 

http://stat545.com/block024_group-nest-split-map.html


```{r}
library(gapminder)
library(tidyverse)

# entry level
gapminder %>%
    group_by(continent) %>%
    summarize_each(funs(min, max), lifeExp)

# nesting
gap_nested <- gapminder %>% 
   group_by(continent, country) %>% 
   nest()

gap_nested[[1, "data"]] #look at data

# apply function map and mutate
(fit <- lm(lifeExp ~ I(year - 1950), data = gap_nested[[1, "data"]]))

# create a function to do the same as above
le_vs_yr <- function(df) {
  lm(lifeExp ~ I(year - 1950), data = df)
}
le_vs_yr(gap_nested[[1, "data"]]) # test function

# use map function to apply function to first two tibbles
fits <- map(gap_nested$data[1:2], le_vs_yr)
fits

# put map inside mutate to run function for every country
(gap_nested <- gap_nested %>% 
   mutate(fit = map(data, le_vs_yr)))

gap_nested[[1, "fit"]] 

```

## Exit Strategy

```{r}
#broom
library(broom)

# use tidy to see results in a nice way
tidy(gap_nested$fit[[1]])

# tidy up the list-column format using above + tidy
(gap_nested <- gap_nested %>% 
  mutate(tidy = map(fit, tidy)))

# now make it readable by unnesting
(gap_coefs <- gap_nested %>% 
   select(continent, country, tidy) %>% 
   unnest(tidy))

(gap_coefs <- gap_coefs %>%
   mutate(term = recode(term,
                        `(Intercept)` = "intercept",
                        `I(year - 1950)` = "slope")))

```

## Examine Results

```{r}

# rename term variable
(gap_coefs <- gap_coefs %>%
   mutate(term = recode(term,
                        `(Intercept)` = "intercept",
                        `I(year - 1950)` = "slope")))

# simplify and reshape the fit data
(gap_ests <- gap_coefs %>% 
   select(continent:estimate) %>% 
   spread(key = term, value = estimate))

# view a summary
gap_ests %>% 
  select(intercept, slope) %>% 
  summary()

# visualize
ggplot(gap_coefs, aes(x = estimate)) +
  geom_density() + geom_rug() + facet_wrap(~ term, scales = "free")


ggplot(gap_ests, aes(x = intercept, y = slope)) +
  geom_point() +
  geom_smooth(se = FALSE, lwd = 2)

```







