---
title: "Buyback Charts"
output:
  html_notebook: null
  html_document: default
  pdf_document: default
  toc: yes
pdf_document: default
number_sections: yes
---

hello world

```{r init,tidy=TRUE}
library(plotly) #for interactive graphs
library(ggplot2) #for better graphs
library(tidyr) #for cleaning datasets
library(psych) #for describe function
library(reshape2) #for reshaping data
library(zoo) #for date functions
library(scales) #for breaks in plots
library(knitr) #for kable
library(ggthemes) #for better themes

s5 <- read.csv("/Volumes/jet/dropbox/asr/datasets/sp500.csv") # read in data

# keep relevant variables
s5<-s5[,c('year','tic','repo','exf_exist_end','ni','totdiv_adj','gsector','dec_mcap')]

# label gsector
s5$gsector <- ordered(s5$gsector,
    levels = c(seq(10,60,5)),
    labels = c("Energy", "Materials", "Industrials", "Consumer Disc.", "Consumer Staples", "Health Care", "Financials", "Info. Tech.", "Telecomm.", "Utilities", "Real Estate"))

# scale repurchases from compustat and create new variables
s5 <- within(s5,{
    repo = repo/1000
    ni = ni/1000
    exf_exist_end = -1*(exf_exist_end/1000000)
    totdiv_adj = totdiv_adj/1000000
    count = 1
    payout = repo + totdiv_adj
    netpayout = totdiv_adj + exf_exist_end
    ei = -1*(repo - exf_exist_end)
    dec_mcap = dec_mcap/1000000
})

# rename columns
colnames(s5) <- c("Year", "Firm", "Repurchases", "Net.Repurchases", "Net.Income", "Dividends","Sector","MCap","Equity.Iss", "Net.Payouts", "Payouts", "Count")

s5_2015 <- subset(s5,Year==2015 & Year<2016) # create 2015 data
s5_3y <- subset(s5,Year>2012 & Year<2016) # create 3 year data
s5_10y <- subset(s5,Year>2005 & Year<2016) # create 10 year data

```

# By Year

```{r aggregate_year}
s5_annt <- aggregate(.~Year, s5_10y, sum) #aggregate by year
s5_anns <- aggregate(.~Year + Sector, s5_10y, sum) #aggregate by year and sector

s5_annt<-subset(s5_annt, select=-c(Firm,Sector)) #remove summed firm/sector
s5_anns<-subset(s5_anns, select=-c(Firm)) #remove summed firm/sector

round(s5_annt,2) # look at annual data
s5_anns[,3:9]<-round(s5_anns[,3:9],2) #round then...
s5_anns #look at annual-sector data
describeBy(s5_anns[,c("Repurchases","Equity.Iss")],s5_anns$Sector, fast=T, mat=T, digits=2)
```

The following two boxplots chart the data presented in the above table. Each sector-box shows the distribution of the 10 observations for each variable.

```{r plot_agg_year}
p_rep <- ggplot(s5_anns, aes(x=Sector, y=Repurchases, fill = Sector)) + geom_boxplot() +
    labs(list(title = "Distribution of Repurchases by Sector and Year (2006-2015)", y = "Billions", x = "")) +
    theme_minimal() + theme(axis.text.x=element_blank())

ggplotly(p_rep)

p_ei <- ggplot(s5_anns, aes(x=Sector, y=Equity.Iss, fill = Sector)) + geom_boxplot() +
    labs(list(title = "Distribution of Equity Issuances by Sector and Year (2006-2015)", y = "Billions", x = "")) +
    theme_minimal() + theme(axis.text.x=element_blank())

ggplotly(p_ei)


```


```{r total_annual}

# pl_fig1 <- ggplot(s5_annt, aes(x=Year)) +
#             labs(list(title = "Repurchases and Dividends (2006-2015)", y = "Billions", x = "")) + 
#             geom_line(aes(y=Repurchases, col='Repurchases')) +
#             geom_line(aes(y=Dividends, col='Dividends')) +
#             theme_minimal() + theme(legend.title=element_blank()) +
#             scale_x_continuous(breaks = seq(2006,2015,1)) +
#             expand_limits( y = c(0,1000))
# 
# ggplotly(pl_fig1, tooltip = c("y","x"))

ay <- list(
  tickfont = list(color = "black"),
  overlaying = "y",
  side = "right",
  title = "second y axis"
)

plot_ly(s5_annt) %>%
    add_lines(x = ~Year, y = ~Repurchases, name = "Repurchases") %>%
    add_lines(x = ~Year, y = ~Dividends, name = "Dividends") %>%
    add_trace(x = ~Year, y = ~MCap, name = "MCap", yaxis = "y2", fill="tozeroy") %>%
  layout(
    title = "Double Y Axis", yaxis2 = ay,
    xaxis = list(title="x")
  )

pl_fig2 <- ggplot(s5_annt, aes(x=Year)) +
            labs(list(title = "Payouts as Percent of Net Income (2006-2015)", y = "Billions", x = "")) + 
            geom_line(aes(y=Payouts/Net.Income , col='Payouts')) +        
            geom_line(aes(y=Repurchases/Net.Income , col='Repurchases')) +
            geom_line(aes(y=Dividends/Net.Income, col='Dividends')) +
            theme_minimal() + theme(legend.title=element_blank()) +
            scale_x_continuous(breaks = seq(2006,2015,1)) +
            expand_limits( y = 0)

ggplotly(pl_fig2, tooltip = c("y","x"))



pl_fig6 <- ggplot(s5_annt, aes(x=Year)) +
            labs(list(title = "Repurchases, Dividends, and Equity Issuances (2006-2015)", y = "Percent", x = "")) + 
            geom_line(aes(y=Repurchases, col='Repurchases')) +
            geom_line(aes(y=Dividends, col='Divdends')) +
            geom_line(aes(y=-1*Equity.Iss, col='Equity Issuances')) +
            theme_minimal() + theme(legend.title=element_blank()) +
            scale_x_continuous(breaks = seq(2006,2015,1)) +
            expand_limits( y = c(0,1000))

ggplotly(pl_fig6, tooltip = c("y","x"))



pl_fig7 <- ggplot(s5_annt, aes(x=Year)) +
            labs(list(title = "Payouts and Net Payouts (2006-2015)", y = "Percent", x = "")) + 
            geom_hline(yintercept = 0, color="grey") +
            geom_line(aes(y=Payouts, col='Payouts')) +
            geom_line(aes(y=Net.Payouts, col='Net Payouts')) +
            theme_minimal() + theme(legend.title=element_blank()) +
            scale_x_continuous(breaks = seq(2006,2015,1)) +
            expand_limits( y = c(0,1000))

ggplotly(pl_fig7, tooltip = c("y","x"))

```

# By Firm

```{r aggregate_firm}

# sum 10 year data
s5_10y <- aggregate(.~Firm + Sector, s5_10y, sum)
# drop if not full 10 years of data
s5_10y <- subset(s5_10y,Count==10)

# kable(describe(s5_10y_ann[2:6], fast = T),digits = 2)

# sum 3 year data
s5_3y <- aggregate(.~Firm + Sector, s5_3y, sum)
# drop if not full 10 years of data
s5_3y <- subset(s5_3y,Count==3)

```

```{r firms_repo}

pldf <- subset(s5_10y,Net.Income>0)

pldf$Firm <- as.character(pldf$Firm) # is this necessary
pldf$Firm <- droplevels(as.factor(pldf$Firm))

# rank payout/ni and sort by rank
pldf$Rank = rank(-pldf$Repurchases, ties.method="first")
pldf <- pldf[order(pldf$Rank),] 
pl_repo10 <- ggplot(pldf, aes(x=Rank, y=Repurchases, fill = Sector,text = paste("Firm:", Firm))) + 
        geom_bar(stat="identity") +
        labs(list(title = "Repurchase Rank (2006-2015)", y = "Billions", x = "")) + 
        theme_minimal() + theme(legend.title=element_blank())

ggplotly(pl_repo10)

# rank payout/ni and sort by rank
pldf <- subset(s5_3y,Net.Income>0)
pldf$Firm <- as.character(pldf$Firm) # is this necessary
pldf$Firm <- droplevels(as.factor(pldf$Firm))
pldf$Rank = rank(-pldf$Repurchases, ties.method="first")
pldf <- pldf[order(pldf$Rank),] 
pl_repo3 <- ggplot(pldf, aes(x=Rank, y=Repurchases, fill = Sector,text = paste("Firm:", Firm))) + 
        geom_bar(stat="identity") +
        labs(list(title = "Repurchase Rank (2013-2015)", y = "Billions", x = "")) + 
        theme_minimal() + theme(legend.title=element_blank())

ggplotly(pl_repo3)

# rank payout/ni and sort by rank
pldf <- subset(s5_2015,Net.Income>0)
pldf$Firm <- as.character(pldf$Firm) # is this necessary
pldf$Firm <- droplevels(as.factor(pldf$Firm))
pldf$Rank = rank(-pldf$Repurchases, ties.method="first")
pldf <- pldf[order(pldf$Rank),] 
pl_repo1 <- ggplot(pldf, aes(x=Rank, y=Repurchases, fill = Sector, text = paste("Firm:", Firm))) + 
        geom_bar(stat="identity") + 
        labs(list(title = "Repurchase Rank (2015)", y = "Billions", x = "")) + 
        #geom_hline(yintercept = mean(pldf$Repurchases), color="black", labels="xx") +
        theme_minimal() + theme(legend.title=element_blank())

ggplotly(pl_repo1)


```


```{r firms_reponet}

pldf <- s5_10y

pldf$Firm <- as.character(pldf$Firm) # is this necessary
pldf$Firm <- droplevels(as.factor(pldf$Firm))

# rank payout/ni and sort by rank
pldf$Rank = rank(-pldf$Repurchases, ties.method="first")
pldf <- pldf[order(pldf$Rank),] 

plot_ly(pldf, x = ~Rank, y = ~Repurchases, type = 'bar', name = 'Repurchases',text = ~Firm) %>%
  add_trace(y = ~Net.Repurchases, name = 'Net Repurchases') %>%
  layout(yaxis = list(title = 'Billions'), barmode = 'overlay')
```












```{r payouts_rank}

pldf <- subset(s5_10y,Net.Income>0)

# create payout/ni
pldf$Payouts.NI = pldf$Payouts/pldf$Net.Income

# create net payout
pldf$Net.Payouts.NI = pldf$Net.Payouts/pldf$Net.Income



# stopped here



# remove outliers
pldf <- subset(pldf,pldf$pay_ni<2)
pldf <- subset(pldf,pldf$netpay_ni<2)

# rank payout/ni and sort by rank
pldf$Rank = rank(pldf$pay_ni)
pldf <- pldf[order(pldf$Rank),] 

#reshape and label
pldf <- pldf %>% gather(key,value, pay_ni, netpay_ni)
pldf[pldf=="pay_ni"]<-"Payouts/NI"
pldf[pldf=="netpay_ni"]<-"Net Payouts/NI"

#plot
#pl_payouts_rank <- pldf %>%
   # ggplot(aes(x=Rank, y=value, colour=key)) +
   # geom_hline(yintercept = 1) + geom_vline(xintercept = 145) + geom_line() +
    #labs(list(title = "Payouts/NI Ranked (2005-2014)", x = "Rank", y = "")) +
    #theme(legend.title=element_blank())

pl_repo <- ggplot(s5_10y_ann, aes(x=Year)) +
            labs(list(title = "Repurchases and Net Repurchases (2005-2014)", y = "Billions", x = "")) + 
            geom_hline(yintercept = 0) +
            geom_line(aes(y=Repurchases , col='Repurchases')) +
            geom_line(aes(y=Net.Repurchases, col='Net Repuchases')) +
            theme(legend.title=element_blank()) +
            scale_x_continuous(breaks = seq(2006,2015,1))

ggplotly(pl_payouts_rank)

```


```{r net_payouts_rank}

pldf <- subset(s5_10y,ni>0)

# create payout/ni
pldf$pay_ni = pldf$payout/pldf$ni

# create net payout
pldf$netpay_ni = pldf$netpayout/pldf$ni

# remove outliers
pldf <- subset(pldf,pldf$pay_ni<2)
pldf <- subset(pldf,pldf$netpay_ni<2)

# rank payout/ni and sort by rank
pldf$Rank = rank(pldf$netpay_ni)
pldf <- pldf[order(pldf$Rank),] 

#reshape and label
pldf <- pldf %>% gather(key,value, pay_ni, netpay_ni)
pldf[pldf=="pay_ni"]<-"Payouts/NI"
pldf[pldf=="netpay_ni"]<-"Net Payouts/NI"

#plot
pl_net_payouts_rank <- pldf %>%
    ggplot(aes(x=Rank, y=value, colour=key)) +
    geom_hline(yintercept = 1) + geom_vline(xintercept = 224) + geom_line() + 
    labs(list(title = "Net Payouts/NI Ranked (2005-2014)", x = "Rank", y = "")) +
    theme(legend.title=element_blank())

ggplotly(pl_net_payouts_rank)

```


```{r gross_net_rank, fig.align = 'center'}

pldf <- subset(s5_10y,ni>0)

# create payout/ni
pldf$pay_ni = pldf$payout/pldf$ni

# create net payout
pldf$netpay_ni = pldf$netpayout/pldf$ni

# remove outliers
pldf <- subset(pldf,pldf$pay_ni<2)
pldf <- subset(pldf,pldf$netpay_ni<2)

# create two dfs with separate rankings
pldfn <- pldf
pldfn$Rank = rank(pldfn$netpay_ni)
pldfn <- pldfn[order(pldfn$Rank),]
pldfn <- pldfn[,c("Rank","netpay_ni")]

pldfg <- pldf
pldfg$Rank = rank(pldfg$pay_ni)
pldfg <- pldfg[order(pldfg$Rank),]
pldfg <- pldfg[,c("Rank","pay_ni")]

#merge two datasets
pldf <- merge(pldfg,pldfn,by="Rank")

#reshape and label
pldf <- pldf %>% gather(key,value, pay_ni, netpay_ni)
pldf[pldf=="pay_ni"]<-"Payouts/NI"
pldf[pldf=="netpay_ni"]<-"Net Payouts/NI"

#plot
pl_gross_net_rank <- pldf %>%
    ggplot(aes(x=Rank, y=value, colour=key)) + 
    geom_hline(yintercept = 1) + geom_vline(xintercept = 224) + geom_vline(xintercept = 145) + geom_line() + 
    labs(list(title = "Linked Ranks (2005-2014)", x = "Rank", y = "")) +
    theme(legend.title=element_blank())
    
ggplotly(pl_gross_net_rank)

```




