---
title: "TS Practice"
author: "Kyle Thomas"
output: html_notebook
---

```{r include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

```{r}
library(xts)
library(zoo)
library(quantmod)
library(astsa)
library(forecast)
```


# Visualizing GDP

```{r}
#get data from FRED
getSymbols("GDP", src="FRED")
```

```{r fig.align = "center"}

#plot 4 alterations of GDP time series
par(mfrow=c(2,2))
plot(GDP) #raw data
plot(log(GDP)) #log data
plot(diff(GDP)) #first-diff data
plot(diff(log(GDP))) #first-diff of log

```

notice log plot is linear

ggplot facet wrap?
plotly multiple plots?
https://plot.ly/r/subplots/

```{r, echo=FALSE,results='hide',fig.keep='all'}
diff_gdp <- diff(GDP)
diff_gdp <- diff_gdp[complete.cases(diff_gdp),] 

ldiff_gdp <- diff(log(GDP))
ldiff_gdp <- ldiff_gdp[complete.cases(ldiff_gdp),] 

acf2(GDP)
acf2(log(GDP))
acf2(diff_gdp)
acf2(ldiff_gdp)

```


need to determine the model
fit model
assess output
plot


```{r}
dgdp <- diff(GDP)
model <- Arima(dgdp, order = c(1,0,0))
fitted <- xts(fitted(model), order.by = index(dgdp))
mf <- merge(model$x, fitted)
plot(mf)
```

```{r}
sarima.for(dgdp, n.ahead = 20, p = 1, d = 0, q = 0)
```


better models